AzureAD/microsoft-authentication-extensions-for-python

msal_extensions/_windows.py
msal_extensions/windows.py
setup.py
tests/test_windows_backend.py

Add DP API Cache

---

msal_extensions/windows.py
tests/test_windows_backend.py

Now that the [GitHub webhook outage is done](https://www.traviscistatus.com/incidents/c9n15td9svp0), it exposed some CI failures that should have been caught in #14! This fixes the TypeError that is causing Windows jobs to fail.

Adding default value for LOCALAPPDATA

---

msal_extensions/token_cache.py
setup.py

Removing `FileTokenCache.add` overload.

---

setup.py

In preparation for releasing 0.1.1, we want to make sure that our constraints are set correctly.

Mark msal 0.5.x as compatible with the extension.

---

.travis.yml
tox.ini

And we can see the [new Python 3.8 test being triggered successfully](https://travis-ci.org/AzureAD/microsoft-authentication-extensions-for-python/builds/598863766?utm_source=github_status&utm_medium=notification).

Also cover Python 3.8 in Test Automation

---

.travis.yml
msal_extensions/__init__.py
setup.py
tox.ini

This release provides:
* same functionality as the previous version
* the test cases are now also run on Python 3.8
* can work with MSAL Python 0.6.0 or higher, until next MSAL Python major version bump

MSAL Python Extensions 0.1.2

---

msal_extensions/cache_lock.py
setup.py

Adding explicit unlocking using portalocker

---

.pylintrc
.travis.yml
msal_extensions/__init__.py
msal_extensions/cache_lock.py
msal_extensions/libsecret.py
msal_extensions/persistence.py
msal_extensions/token_cache.py
sample/persistence_sample.py
sample/token_cache_sample.py
setup.py
tests/test_agnostic_backend.py
tests/test_persistence.py
tox.ini

Description
----------------
* ~The CI tests are currently failing, but only because some styling error. I'll fix it soon. This does NOT block your review.~ Fixed.
* So far I run pre-existing `test_agnostic_backend.py` to test it manually on Linux Desktop, and "it seems to work"<sup>TM</sup>
* I have ~NOT yet~ tested it in SSH console. Encryption is NOT available in an SSH console, and this exception will be raised, as expected: `gi.repository.GLib.GError: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)`
* ~I'll~ add more API docs ~later~ below.
* This PR will fix #4
Usage
---------
1. The main interface of MSAL Extension for Python (MSAL EX Python) has historically been some platform-dependent `TokenCache` classes, whose instances can then be fed into MSAL Python's …

Encryption on Linux based on libsecret

---

.pylintrc
.travis.yml
msal_extensions/__init__.py
msal_extensions/cache_lock.py
msal_extensions/libsecret.py
msal_extensions/persistence.py
msal_extensions/token_cache.py
sample/persistence_sample.py
sample/token_cache_sample.py
setup.cfg
setup.py
tests/test_agnostic_backend.py
tests/test_persistence.py
tox.ini

This release provides:
* New feature: Support token cache encryption when running on Linux Desktop (#4, #44)
* Bug fix: The cache lock was not properly removed on Windows 10 (#42, #43)
* Change: A new set of API `PersistedTokenCache` is provided. Previous API is now deprecated and will be removed in next major release which will likely come within a month: `WindowsTokenCache`, `OSXTokenCache`, `UnencryptedTokenCache`, `FileTokenCache` and `TokenCache`.

Release 0.2.0

---

msal_extensions/libsecret.py
sample/persistence_sample.py
setup.py

Per request from Azure SDK team, we no longer require `PyGObject` package at installation time. For this change, we also fine tune the run-time errors.
@chlowell please see if this is what you want.

Only require PyGObject at runtime

---

setup.py

Per [a discussion](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/43#issuecomment-617739430) and its subsequent off-line discussion with @bluca , we realize that package maintainers on Linux might not want to aggressively upgrade a dependency to its latest version. So, in this PR, we make it clear that the portalocker 1.6.0 dependency requirement is only needed on Windows.

Use more precise dependency declaration

---

msal_extensions/__init__.py
msal_extensions/cache_lock.py
setup.py

* Functionally the same as 0.2.0, but we change the installation-time and import-time dependency of `PyGObject` to run-time dependency. This would make the installation easier for those customers who do not necessarily need to use the Encryption on Linux. (#47)
* The version 1.6.0+ of upstream package `portalocker` is only required on Windows. Other platforms remain with portalocker 1.0.0+. (#49)

Release 0.2.1

---

msal_extensions/cache_lock.py

Support for passing parameters through to the open syscall was added in
version 1.4.0. Check before using this feature to keep backward compatibility.
https://github.com/WoLpH/portalocker/commit/721b3309c2
The dependency would cut off the current Debian Stable and Ubuntu before 19.10

Restore compatibility with portalocker < 1.4.0

---

msal_extensions/token_cache.py
tests/test_agnostic_backend.py

On Python 3, calling `PersistedTokenCache.find()` on a nonexistent cache file is a no-op, so this code works:
```py
from msal_extensions import FilePersistence, PersistedTokenCache
persistence = FilePersistence('nope')
cache = PersistedTokenCache(persistence=persistence)
cache.find('')
```
On Python 2.7 it raises a platform-specific error: `WindowsError` on Windows, `OSError` on Linux (I haven't tried it on macOS). The difference in behavior is due to `PersistedTokenCache` anticipating `IOError` when a file isn't found. Neither `WindowsError` nor `OSError` is a subclass of `IOError`. All these errors are subclasses of `EnvironmentError` though, and that class has the `errno` attribute, so a simple fix is to handle `EnvironmentError` here.

Handle file not found exceptions on Python 2.7

---

msal_extensions/persistence.py
msal_extensions/token_cache.py
tests/test_persistence.py

Hi Abhi, while pondering #65 , I feel uncomfortable of its introduction of a new `None` return value, and today I also realize that such a new behavior in the other 3 persistence flavours are inconsistent with `FilePersistence`. So, in this PR, I'm experimenting a different approach, to NOT introduce the `None` as a successful return value, but rather raise exception - this time we raise a common `IOError`. Test cases are not yet added. Please review this proof-of-concept.
UPDATE at 8/28: We settled with a new exception `PersistenceNotFound` for the scenario described in #64 
This PR will replace/close #65, and resolve #64.

Unified exception when load() is called before save()

---

msal_extensions/persistence.py

While I'm planning the version number of our upcoming MSAL EX release in my head, I realized that our #67 introduced a subtle incompatibility. This PR should fix that. Please review.
Besides, if everything goes well, we can start a 0.2.3 release next Monday.

Change PersistenceNotFound's base from OSError to IOError

---

setup.cfg
setup.py

Mention license. Also add project_urls which would probably trigger an automatic project home page link being rendered in PyPI. This would fix #75 , although we would only see the result at next release.

Mention licence

---

.travis.yml

And we have to also disable tests on Python 3.6, for now, due to the unable-to-compile-cryptography issue.

Upgrade pip to overcome some Travis CI error

---

msal_extensions/persistence.py

Note that the bug remains under Python 2
Addresses #83

Fixed failure when a user's home dir is a drive root on Windows

---

.github/workflows/python-package.yml
.pylintrc
msal_extensions/cache_lock.py
msal_extensions/libsecret.py
msal_extensions/osx.py
msal_extensions/persistence.py

* Upgraded to the latest version (2.8.2 as of today) of `pylint`, which is one of the [popular linters in Python](https://realpython.com/python-code-quality/#comparing-python-linters).
* Addressed the issues reported by it.
This is an attempt to address https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/264

Enable linter

---

msal_extensions/windows.py

Specify memcpy argtypes

---

msal_extensions/libsecret.py

This may fix #92 .
@chlowell , continuing our conversation in #92, this PR currently chooses to not use `six` (which is never in MSAL or MSAL EX dependency, by the way).

Raise without log polluting the console

---

setup.py

Thanks @dhirschfeld for bringing #94 to our attention. It turns out, our attempt in #95 was not quite there yet, so my offline trial-and-error led me to this PR. It should work, and it will close #94 and close #95.
P.S.: After merging this PR, the change will not immediately go live, but it will be included in our next release.

Allow portalocker 2 on Python 3.5+

---

msal_extensions/token_cache.py

The [original plan](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/77#issuecomment-698021810) was trying to hide `deserialize()` (and also `serialize()`) from MSAL EX's `PersistedTokenCache`. But that requires more churn (in terms of both implementation and customer impact). So, this PR goes with an easier approach - at least for now - to document the known behaviors. This PR will resolve #77.

Document the design goals and scopes

---

msal_extensions/token_cache.py

An attempt to bypass the locking behavior when reading token cache. Most of the time, token cache is only serving read operation, so conceptually we will only need to lock once per hour. This would likely improve the concurrency a lot.
@jiasli

Skip read lock to improve concurrency

---

msal_extensions/persistence.py
sample/persistence_sample.py
sample/token_cache_sample.py
tests/test_persistence.py

Az CLI uses 2 instances of persistence for different data, stored in different files. @jiasli found it unobvious that he would need to use different `service_name` and `account_name` when running on mac. This PR attempts to hide/handle this detail, by automatically generate those 2 parameters based on the (signal) file location.
1. Historically, before we introduced all those platform-dependent parameters, there was a unified `TokenCache` interface across all platforms.
2. Later when we added (more and more) platform-dependent parameters, we attempted to keep a similar cross-platform `build_persistence()` helper but it did not really hide all those platform-dependent details, it merely becomes a union of all parameters.
```python
def build_persistence(
...,
entropy='',  # For Windows …
```

Making all platform-dependent parameters optional

---

msal_extensions/persistence.py

The file containing token cache (or arbitrary data) will be created with permission `600` when running on UNIX.
Once merged, this PR will close #106.
@jiasli . CC: @bgavrilMS , @Avery-Dunn

Use 600 mode on Unix

---

.pylintrc
msal_extensions/persistence.py
msal_extensions/windows.py
tests/test_persistence.py
tox.ini

This PR provides user-friendly exception messages for real-world observation: https://github.com/Azure/azure-cli/issues/20231, https://github.com/Azure/azure-cli/issues/20759, and https://github.com/Azure/azure-cli/issues/21010 . The default error messages is not (and can not) be specific to Azure CLI, but Azure CLI can choose to catch the 2 new exceptions `PersistenceEncryptionError` and `PersistenceDecryptionError`, and then emit their own error messages.
CC: @jiasli

Provide catch-able exceptions for 2 dpapi errors

---

msal_extensions/__init__.py
msal_extensions/persistence.py
msal_extensions/token_cache.py
sample/persistence_sample.py
sample/token_cache_sample.py
tests/test_agnostic_backend.py
tests/test_macos_backend.py
tests/test_windows_backend.py

* Add a new `build_encrypted_persistence()` factory function into the public API. This will resolve #87.
* Also remove some old APIs which has been deprecated for 2 years now
<sub>Note-to-self: We will need to change the merge base once that base-branch being merged.</sub>

Persistence factory

---

msal_extensions/persistence.py
msal_extensions/windows.py

Since period is already in https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/e30080b5c1b3e2c801bf371631c3c7afd4cda27a/msal_extensions/windows.py#L44
The error message becomes 
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError: 'C:\\Users\\xxx\\.azure\\msal_token_cache.bin'
```

Refine error messages of `PersistenceEncryptionError` and `PersistenceDecryptionError`

---

.github/workflows/python-package.yml
msal_extensions/cache_lock.py
setup.py

* Closes https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/121
* Closes https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/118

Remove use of distutils

---

.github/workflows/python-package.yml
README.md
setup.cfg
setup.py

The existing test automation were failing due to the infrastructure already dropped Python 2.7 support.

Dropping Python 2.7

---

.github/workflows/python-package.yml
setup.cfg
tox.ini

This PR updates the trove classifiers to specify which versions are supported.
It also adds 3.10 to the build matrix.

Update trove classifiers and build matrix for Python 3.10

---

msal_extensions/cache_lock.py
setup.py

`packaging` was only used as a dependency to check for the version of `portalocker` in use.
This drops that dependency and instead corrects the minimum version of `portalocker` to the one checked here.
It should be safe to depend on a version of `portalocker` that has been out for 3 years at this point, and is not quite as intrusive as #117 that would remove `portalocker` altogether (and in all honesty, that PR has been out there for a year, with no sign of merging).

Set proper lower bound for `portalocker` dependency, drop `packaging` dependency

---

docker_run.sh
msal_extensions/__init__.py
msal_extensions/token_cache.py
setup.py
tests/test_agnostic_backend.py
tests/test_macos_backend.py
tests/test_windows_backend.py

This PR will fix #127 . The fix will be shipped as MSALEX 1.2.0a1 within this month. And then next month both MSAL and MSAL EX will rename the affected function from `_find()` to `iter()`.
CC @jiasli

Switch to MSAL 1.27+'s TokenCache._find()

---

setup.py

See https://github.com/wolph/portalocker/releases/tag/v3.0.0; portalocker 3 drops support for end-of-life Python versions older than 3.9. The older portalocker versions allowed in the range still cover these Python interpreter versions.

Allow portalocker version 3

---

.gitignore
Dockerfile
docker_run.sh
msal_extensions/__init__.py
msal_extensions/cache_lock.py
msal_extensions/filelock.py
msal_extensions/libsecret.py
msal_extensions/token_cache.py
setup.py
tests/cache_file_generator.py
tests/http_client.py
tests/test_agnostic_backend.py
tests/test_cache_lock_file_perf.py
tests/test_crossplatlock.py
tox.ini

This is currently an experimental PR. It will not be merged, not until we receive some test feedback. To beta test this PR, you will need to pull it from its feature branch.
Usage: There is no API change. MSAL EX will automatically utilize portalocker when portalocker is available in current environment, and switch to a new portalocker-less implementation otherwise.
Note:
* A lock mechanism is only used to guard against garbled data due to concurrent read/write. A lock mechanism in itself does not make the higher level application more or less performant. When your app is overloaded, previously (i.e. before this PR) you will see `portalocker.exceptions.LockException` which means the locking mechanism is doing its job. After this PR, under the *same* heavy load, you will see `LockError` …

Make portalocker optional

---

sample/token_cache_sample.py

It's just a tiny fix to add a missing import.
The previous code would fail with:
```
NameError: name 'PersistedTokenCache' is not defined
```

Add missing import in token_cache_sample
